Code Generated by Sidekick is for learning and experimentation purposes only. For other use cases, please see the guidance linked here for accessing and using the Deloitte-approved tools GitHub Copilot or AWS Codewhisperer.
Below is a drop-in “v2” of your Streamlit app that adds GenZ-office bot features: persona/mode switch, vibe meter, roast level (safe), /slang + /questions, /todo manager, /actions extractor, /recap summary, time-boundary nudges (after-hours), basic analytics, and chat export/import—while keeping your FAAH + Celebrate logic.
Python# Code Generated by Sidekick is for learning and experimentation purposes only.
import base64
import datetime as dt
import io
import json
import math
import random
import re
import wave
from dataclasses import dataclass

import streamlit as st
import streamlit.components.v1 as components

# =============================
# Config
# =============================
st.set_page_config(page_title="Office GenZ Bot (FAAH + Celebrate)", layout="centered")
random.seed()

# =============================
# UI (dark bg + readable glass surfaces)
# =============================
st.markdown(
    """
<style>
/* Code Generated by Sidekick is for learning and experimentation purposes only. */
.stApp{
  background:
    radial-gradient(900px 520px at 12% 8%, rgba(98,181,229,0.22), transparent 60%),
    radial-gradient(800px 520px at 92% 12%, rgba(134,188,37,0.18), transparent 62%),
    radial-gradient(800px 520px at 50% 92%, rgba(255,209,0,0.10), transparent 62%),
    linear-gradient(180deg, #0B1220 0%, #0A0F16 65%, #0B1220 100%);
}
:root{
  --ink:#0B1220;
  --muted:#4B5563;
  --line:rgba(11,18,32,.10);
  --glass:rgba(255,255,255,.92);
  --glass2:rgba(255,255,255,.80);
  --shadow: 0 14px 46px rgba(0,0,0,.22);
}
.block-container{ padding-top: 1.1rem; max-width: 980px; }

.hero{
  border: 1px solid var(--line);
  background: var(--glass);
  border-radius: 18px;
  padding: 14px 16px 12px 16px;
  box-shadow: var(--shadow);
  backdrop-filter: blur(10px);
}
.title{ font-size: 1.45rem; font-weight: 900; margin:0; color: var(--ink) !important; }
.sub{ margin-top: 6px; font-size: .95rem; color: var(--muted) !important; }
.kbd{
  display:inline-block; padding: 2px 8px; border-radius: 10px;
  border: 1px solid var(--line); background: rgba(255,255,255,.70);
  font-size: .84rem; margin-right: 6px; color: var(--ink) !important;
}

.card{
  margin-top: 12px;
  border: 1px solid var(--line);
  background: var(--glass2);
  border-radius: 18px;
  padding: 12px 12px 8px 12px;
  box-shadow: var(--shadow);
  backdrop-filter: blur(10px);
}
.small{ font-size:.90rem; color: var(--muted) !important; }

section[data-testid="stSidebar"]{
  background: rgba(255,255,255,.86) !important;
  border-right: 1px solid var(--line);
  backdrop-filter: blur(10px);
}

div[data-testid="stChatMessage"]{
  border: 1px solid var(--line) !important;
  background: rgba(255,255,255,.92) !important;
  border-radius: 16px !important;
  box-shadow: 0 10px 28px rgba(0,0,0,.12);
}
div[data-testid="stChatMessage"] *{ color: var(--ink) !important; }

div[data-testid="stChatInput"]{
  border: 1px solid var(--line) !important;
  border-radius: 14px !important;
  background: rgba(255,255,255,.92) !important;
  box-shadow: 0 10px 28px rgba(0,0,0,.12);
}
div[data-testid="stChatInput"] textarea{ color: var(--ink) !important; }
</style>
""",
    unsafe_allow_html=True,
)

# =============================
# State
# =============================
def ss_init():
    if "messages" not in st.session_state:
        st.session_state.messages = []
    if "sound_unlocked" not in st.session_state:
        st.session_state.sound_unlocked = False
    if "audio_nonce" not in st.session_state:
        st.session_state.audio_nonce = 0

    # FAAH upload
    if "faah_upload_bytes" not in st.session_state:
        st.session_state.faah_upload_bytes = None
        st.session_state.faah_upload_mime = None
        st.session_state.faah_upload_name = None

    # Celebrate sound upload (optional)
    if "celebrate_upload_bytes" not in st.session_state:
        st.session_state.celebrate_upload_bytes = None
        st.session_state.celebrate_upload_mime = None
        st.session_state.celebrate_upload_name = None

    # GenZ bot settings
    if "mode" not in st.session_state:
        st.session_state.mode = "GenZ"  # Client-safe | GenZ | Hinglish | Roast-lite
    if "roast_level" not in st.session_state:
        st.session_state.roast_level = 1  # 0..3 (kept safe)
    if "vibe" not in st.session_state:
        st.session_state.vibe = 3  # 1..5
    if "work_start" not in st.session_state:
        st.session_state.work_start = 10
    if "work_end" not in st.session_state:
        st.session_state.work_end = 19

    # Utilities
    if "_queued_input" not in st.session_state:
        st.session_state._queued_input = None
    if "todos" not in st.session_state:
        st.session_state.todos = []  # list[dict{id:int, text:str, done:bool, ts:str}]
    if "stats" not in st.session_state:
        st.session_state.stats = {
            "faah_count": 0,
            "good_count": 0,
            "msg_count": 0,
            "top_triggers": {},  # pattern -> count
        }

ss_init()

# =============================
# Audio helpers (FAAH upload + synth fallback)
# =============================
AUTOPLAY_NOTE = "If sound doesn’t autoplay: click Enable Sound once (browser rule)."

def _to_wav_bytes(sr: int, samples_f32: list[float]) -> bytes:
    pcm = bytearray()
    for x in samples_f32:
        x = max(-1.0, min(1.0, float(x)))
        i = int(x * 32767.0)
        pcm += int(i).to_bytes(2, "little", signed=True)
    buf = io.BytesIO()
    with wave.open(buf, "wb") as wf:
        wf.setnchannels(1)
        wf.setsampwidth(2)
        wf.setframerate(sr)
        wf.writeframes(bytes(pcm))
    return buf.getvalue()

def make_silence_wav(ms: int = 80) -> bytes:
    sr = 22050
    n = int(sr * (ms / 1000.0))
    return _to_wav_bytes(sr, [0.0] * n)

def make_faah_synth_wav() -> bytes:
    # Short comedic down-sweep + noise burst
    sr, dur = 22050, 0.26
    n = int(sr * dur)
    out = []
    f0, f1 = 760.0, 150.0
    phase = 0.0
    for i in range(n):
        t = i / sr
        freq = f0 * ((f1 / f0) ** (t / dur))
        phase += (2.0 * math.pi * freq) / sr
        sweep = math.sin(phase)
        noise = (random.random() * 2.0 - 1.0) * 0.09
        env = math.exp(-8.5 * t)
        out.append(math.tanh(2.2 * (0.92 * sweep + noise)) * env)
    return _to_wav_bytes(sr, out)

def make_celebrate_ding_wav() -> bytes:
    # A tiny "ding" chord
    sr, dur = 22050, 0.22
    n = int(sr * dur)
    out = []
    freqs = [880.0, 1108.7, 1320.0]
    for i in range(n):
        t = i / sr
        env = math.exp(-10.0 * t)
        s = 0.0
        for f in freqs:
            s += math.sin(2.0 * math.pi * f * t)
        s = (s / len(freqs)) * env
        out.append(math.tanh(1.8 * s))
    return _to_wav_bytes(sr, out)

def get_faah_bytes() -> tuple[bytes, str, str]:
    if st.session_state.faah_upload_bytes:
        return (
            st.session_state.faah_upload_bytes,
            st.session_state.faah_upload_mime or "audio/mpeg",
            f"FAAH (uploaded: {st.session_state.faah_upload_name})",
        )
    return (make_faah_synth_wav(), "audio/wav", "FAAH (synth)")

def get_celebrate_bytes() -> tuple[bytes, str, str]:
    if st.session_state.celebrate_upload_bytes:
        return (
            st.session_state.celebrate_upload_bytes,
            st.session_state.celebrate_upload_mime or "audio/mpeg",
            f"Celebrate (uploaded: {st.session_state.celebrate_upload_name})",
        )
    return (make_celebrate_ding_wav(), "audio/wav", "Celebrate (ding synth)")

def js_play_audio_now(audio_bytes: bytes, mime: str, nonce: int, volume: float = 1.0):
    # Uses JS Audio() play. Works ONLY after a user gesture in most browsers.
    b64 = base64.b64encode(audio_bytes).decode("ascii")
    vol = max(0.0, min(1.0, float(volume)))
    html = f"""
    <script>
      (async () => {{
        try {{
          const a = new Audio("data:{mime};base64,{b64}");
          a.volume = {vol};
          await a.play();
        }} catch (e) {{
          console.log("autoplay blocked", e);
        }}
      }})();
    </script>
    """
    components.html(html, height=0, width=0)

def play_audio_with_fallback(audio_bytes: bytes, mime: str, label: str, try_autoplay: bool, volume: float = 1.0):
    st.caption(label)
    st.audio(audio_bytes, format=mime)
    if try_autoplay and st.session_state.sound_unlocked:
        st.session_state.audio_nonce += 1
        js_play_audio_now(audio_bytes, mime, st.session_state.audio_nonce, volume=volume)
    elif try_autoplay and (not st.session_state.sound_unlocked):
        st.info(AUTOPLAY_NOTE)

def play_faah_immediately(try_autoplay: bool):
    b, m, label = get_faah_bytes()
    play_audio_with_fallback(b, m, label, try_autoplay=try_autoplay, volume=1.0)

def play_celebrate_immediately(try_autoplay: bool):
    b, m, label = get_celebrate_bytes()
    play_audio_with_fallback(b, m, label, try_autoplay=try_autoplay, volume=0.9)

# =============================
# Triggers
# =============================
TRIGGERS = [
    (r"\bclient\b.*\bnew ideas?\b", "client_new_ideas"),
    (r"\bclient\b.*\bmore ideas?\b", "client_more_ideas"),
    (r"\bclient\b.*\bbrainstorm\b", "client_brainstorm"),
    (r"\bclient\b.*\bfresh ideas?\b", "client_fresh_ideas"),
    (r"\bclient\b.*\binnovate\b", "client_innovate"),
    (r"\bclient wants new ideas\b", "client_wants_new_ideas"),
    (r"\bby eod\b|\beod\b", "eod"),
    (r"\basap\b", "asap"),
    (r"\bsmall change\b", "small_change"),
    (r"\bquick deck\b", "quick_deck"),
    (r"\bquick call\b|\bhop on\b.*\bcall\b", "quick_call"),
    (r"\bcircle back\b", "circle_back"),
    (r"\bkeep it simple\b.*\bimpactful\b", "simple_impactful"),
    (r"\bmake it pop\b", "make_it_pop"),
    (r"\bone last thing\b", "one_last_thing"),
    (r"\bpls fix\b|\bplz fix\b|\bplease fix\b", "pls_fix"),
    (r"\brebaseline\b", "rebaseline"),
    (r"\bscope change\b|\bchange request\b", "scope_change"),
]

GOOD_NEWS_PATTERNS = [
    r"\bgood news\b",
    r"\bwe won\b|\bwe won the\b",
    r"\bapproved\b|\bapproval\b|\bgreen light\b",
    r"\bsigned\b|\bcontract signed\b|\bpo issued\b",
    r"\bgo[- ]live\b|\blaunch(ed)?\b",
    r"\bkudos\b|\bshoutout\b|\bappreciation\b",
    r"\bclient loved\b|\bclient happy\b|\bpositive feedback\b",
    r"\buat passed\b|\bpassed\b.*\buat\b",
]

def should_play_faah(text: str) -> tuple[bool, list[str]]:
    t = (text or "").lower().strip()
    hits = []
    for patt, key in TRIGGERS:
        if re.search(patt, t):
            hits.append(key)
    return (len(hits) > 0, hits)

def is_good_news(text: str) -> bool:
    t = (text or "").lower().strip()
    return any(re.search(p, t) for p in GOOD_NEWS_PATTERNS)

# =============================
# Slang + question banks
# =============================
SLANG_BANK = {
    "Meetings": [
        ("circle back", "revisit later"),
        ("touch base / sync", "quick alignment"),
        ("parking lot", "defer topic"),
        ("hard stop", "must leave on time"),
        ("take offline", "separate conversation"),
    ],
    "Delivery": [
        ("EOD / COB", "end of day / close of business"),
        ("ASAP", "urgent (often vague)"),
        ("blocker", "thing stopping progress"),
        ("dependencies", "waiting on something"),
        ("client-ready", "polished and safe to share"),
    ],
    "Workstyle": [
        ("bandwidth", "capacity/time"),
        ("DRI / owner", "directly responsible person"),
        ("deep dive", "detailed review"),
        ("in the weeds", "too much detail"),
        ("quick wins", "small, fast improvements"),
    ],
}

QUESTION_BANK = {
    "Status": [
        "What’s the status on X?",
        "Any blockers or risks?",
        "What’s the plan for today?",
        "Who owns next steps?",
    ],
    "Comms": [
        "Rewrite this to be client-safe.",
        "Make this message firm but polite.",
        "Draft a follow-up email with actions.",
        "Summarize this thread in five bullets.",
    ],
    "Meetings": [
        "Create a 30-minute agenda for X.",
        "Write minutes from these notes.",
        "What decisions do we need today?",
        "Draft meeting invite text.",
    ],
    "PMO": [
        "Create a RAID entry for this issue.",
        "Build a simple two-week workplan.",
        "List assumptions and dependencies.",
        "Make a RACI for this process.",
    ],
}

# =============================
# Tone packs (kept safe; no insults; no stereotypes)
# =============================
TONE = {
    "Client-safe": {
        "normal": [
            "Acknowledged. I’ll keep it clear and client-ready.",
            "Got it. I’ll propose a crisp next step and owner.",
            "Understood. I’ll structure this for fast review.",
        ],
        "faah": [
            "Noted. I’ll propose options and trade-offs to contain scope.",
            "Understood. I’ll draft a quick, decision-focused response.",
            "Got it. I’ll keep it simple, measurable, and feasible.",
        ],
        "good": [
            "Great—congrats on the approval. I’ll draft a concise update and next steps.",
            "Good news. I’ll capture the decision and document follow-ups.",
        ],
    },
    "GenZ": {
        "normal": [
            "Copy. Keeping it short, clean, and usable.",
            "Locked. I’ll make it easy to ship.",
            "Got it. Minimal drama, maximum clarity.",
        ],
        "faah": [
            "Okay—scope alarm noted. I’ll give you a tight structure and options.",
            "Heard. I’ll keep it fast, practical, and defensible.",
            "Understood. I’ll help you push back without friction.",
        ],
        "good": [
            "Win. I’ll write the update and next steps.",
            "Nice. Let’s capture the decision while it’s fresh.",
        ],
    },
    "Hinglish": {
        "normal": [
            "Noted—clean, crisp, client-safe.",
            "Got it. Short and usable rakhenge.",
            "Okay. No drama, only deliverables.",
        ],
        "faah": [
            "FAAH vibes. Scope ko contain karte hain—options de deta hoon.",
            "Samjha. Fast structure + pushback line de deta hoon.",
            "Done. Simple bhi, impactful bhi—balanced version banate hain.",
        ],
        "good": [
            "W. Ab decision + next steps lock karte hain.",
            "Client happy? Perfect. Update crisp bhejte hain.",
        ],
    },
    "Roast-lite": {
        "normal": [
            "Got it. I’ll translate this into something humans can execute.",
            "Understood. Turning chaos into a checklist.",
            "Copy. I’ll make it readable and review-proof.",
        ],
        "faah": [
            "Noted. Another ‘small change’—I’ll protect scope and sanity.",
            "Understood. I’ll give you a plan that survives the next ‘one last thing’.",
            "Copy. I’ll draft a crisp response before the calendar attacks again.",
        ],
        "good": [
            "Good outcome. Let’s document it before it becomes ‘just a draft’.",
            "Nice. We’ll lock the decision and avoid accidental scope expansion.",
        ],
    },
}

# =============================
# Utilities: time boundaries, actions, recap, todos
# =============================
def in_work_hours(now: dt.datetime) -> bool:
    return st.session_state.work_start <= now.hour < st.session_state.work_end

def asks_urgent(text: str) -> bool:
    t = (text or "").lower()
    return bool(re.search(r"\basap\b|\beod\b|\bby eod\b|\burgent\b|\bright now\b|\btoday\b", t))

def boundary_nudge(now: dt.datetime) -> str | None:
    # After-hours: offer a polite pushback template
    if in_work_hours(now):
        return None
    return (
        "Time check: this looks urgent and it’s after-hours. "
        "If you want, I can draft a polite pushback: "
        "‘I can share an initial cut by tomorrow [time], and a refined version by [date]—does that work?’"
    )

def extract_action_items(messages: list[dict]) -> list[str]:
    # Lightweight heuristic extractor from recent user messages
    recent = [m["content"] for m in messages[-20:] if m.get("role") == "user"]
    text = "\n".join(recent).lower()
    candidates = []

    # Patterns like: "please X", "need to X", "can you X", "action: X"
    patt_list = [
        r"(?:please|plz|pls)\s+([^\n\.]{6,120})",
        r"(?:need to|we need to|i need to)\s+([^\n\.]{6,120})",
        r"(?:can you|could you)\s+([^\n\?]{6,120})",
        r"(?:action item|action items|next step|next steps)\s*[:\-]\s*([^\n]{6,160})",
    ]
    for p in patt_list:
        for m in re.finditer(p, text):
            s = m.group(1).strip()
            s = re.sub(r"\s+", " ", s)
            s = s.rstrip(" .;:")
            if len(s) >= 6:
                candidates.append(s)

    # De-dupe while preserving order
    out = []
    seen = set()
    for c in candidates:
        key = c[:80]
        if key not in seen:
            seen.add(key)
            out.append(c)
    return out[:12]

def recap_messages(messages: list[dict]) -> str:
    # Simple recap using the last few user prompts + detected actions
    recent_user = [m["content"].strip() for m in messages[-12:] if m.get("role") == "user"]
    recent_user = [x for x in recent_user if x]
    actions = extract_action_items(messages)
    lines = []
    lines.append("Recap (latest):")
    if recent_user:
        lines.append("Context:")
        for x in recent_user[-5:]:
            x1 = re.sub(r"\s+", " ", x)
            lines.append(f"- {x1[:160]}")
    if actions:
        lines.append("\nLikely action items:")
        for a in actions[:8]:
            lines.append(f"- {a}")
    lines.append("\nIf you paste notes, I can format minutes/RAID/status.")
    return "\n".join(lines)

def todo_add(text: str):
    tid = (st.session_state.todos[-1]["id"] + 1) if st.session_state.todos else 1
    st.session_state.todos.append(
        {"id": tid, "text": text.strip(), "done": False, "ts": dt.datetime.now().strftime("%H:%M")}
    )

def todo_done(tid: int) -> bool:
    for t in st.session_state.todos:
        if t["id"] == tid:
            t["done"] = True
            return True
    return False

def todo_list() -> str:
    if not st.session_state.todos:
        return "Todo list is empty. Use: /todo add <task>"
    lines = ["Todos:"]
    for t in st.session_state.todos[-20:]:
        flag = "DONE" if t["done"] else "OPEN"
        lines.append(f"- [{flag}] #{t['id']} {t['text']}")
    return "\n".join(lines)

def format_slang() -> str:
    lines = ["Common office slang (quick):"]
    for cat, items in SLANG_BANK.items():
        lines.append(f"\n{cat}:")
        for term, meaning in items:
            lines.append(f"- {term}: {meaning}")
    lines.append("\nTip: ask ‘/questions’ for common prompts.")
    return "\n".join(lines)

def format_questions() -> str:
    lines = ["Common office questions (prompt ideas):"]
    for cat, qs in QUESTION_BANK.items():
        lines.append(f"\n{cat}:")
        for q in qs:
            lines.append(f"- {q}")
    return "\n".join(lines)

def set_mode_from_cmd(cmd: str) -> str:
    # /mode genz | client | hinglish | roast
    parts = cmd.strip().split()
    if len(parts) < 2:
        return f"Current mode: {st.session_state.mode}. Use: /mode genz|client|hinglish|roast"
    m = parts[1].lower()
    mapping = {
        "genz": "GenZ",
        "client": "Client-safe",
        "clientsafe": "Client-safe",
        "hinglish": "Hinglish",
        "roast": "Roast-lite",
        "roastlite": "Roast-lite",
    }
    if m not in mapping:
        return "Unknown mode. Use: /mode genz|client|hinglish|roast"
    st.session_state.mode = mapping[m]
    return f"Mode set: {st.session_state.mode}"

def set_vibe_from_cmd(cmd: str) -> str:
    # /vibe 1..5
    parts = cmd.strip().split()
    if len(parts) < 2:
        return f"Current vibe: {st.session_state.vibe}/5. Use: /vibe 1..5"
    try:
        v = int(parts[1])
        v = max(1, min(5, v))
        st.session_state.vibe = v
        return f"Vibe set: {st.session_state.vibe}/5"
    except Exception:
        return "Invalid vibe. Use: /vibe 1..5"

# =============================
# Office response engine
# =============================
def pick_tone(kind: str) -> str:
    mode = st.session_state.mode
    pack = TONE.get(mode, TONE["GenZ"])
    choices = pack.get(kind, pack["normal"])
    return random.choice(choices)

def office_reply(user_text: str, faah_hit: bool, good_hit: bool) -> str:
    t = (user_text or "").strip()
    low = t.lower()

    now = dt.datetime.now()

    # Commands
    if low in ("/help", "help"):
        return (
            "Commands:\n"
            "- /help\n"
            "- /faah (play FAAH)\n"
            "- /mode genz|client|hinglish|roast\n"
            "- /vibe 1..5\n"
            "- /slang\n"
            "- /questions\n"
            "- /actions\n"
            "- /recap\n"
            "- /todo add <task>\n"
            "- /todo list\n"
            "- /todo done <id>\n\n"
            "Ask for: email / standup / agenda / RAID / notes / slides / workplan."
        )

    if low == "/faah":
        return "FAAH triggered (manual)."

    if low.startswith("/mode"):
        return set_mode_from_cmd(low)

    if low.startswith("/vibe"):
        return set_vibe_from_cmd(low)

    if low == "/slang":
        return format_slang()

    if low == "/questions":
        return format_questions()

    if low == "/actions":
        items = extract_action_items(st.session_state.messages)
        if not items:
            return "No obvious action items found yet. Paste notes or requests."
        return "Detected action items:\n" + "\n".join([f"- {x}" for x in items])

    if low == "/recap":
        return recap_messages(st.session_state.messages)

    if low.startswith("/todo"):
        parts = t.split(maxsplit=2)
        if len(parts) == 1:
            return "Use: /todo add <task> | /todo list | /todo done <id>"
        sub = parts[1].lower()
        if sub == "add":
            if len(parts) < 3 or not parts[2].strip():
                return "Usage: /todo add <task>"
            todo_add(parts[2])
            return f"Added todo #{st.session_state.todos[-1]['id']}."
        if sub == "list":
            return todo_list()
        if sub == "done":
            if len(parts) < 3:
                return "Usage: /todo done <id>"
            try:
                tid = int(parts[2])
                ok = todo_done(tid)
                return "Marked done." if ok else "Todo id not found."
            except Exception:
                return "Invalid id. Usage: /todo done <id>"
        return "Unknown /todo command. Use: add|list|done"

    # Time boundary nudge (after-hours + urgent)
    nudge = boundary_nudge(now) if asks_urgent(t) else None

    # Good news path
    if good_hit:
        base = pick_tone("good")
        extra = "Share: what was approved + metric + next step. I’ll draft a client-safe update."
        return f"{base}\n\n{extra}"

    # Intent handlers
    if any(k in low for k in ["standup", "status update", "daily update", "scrum"]):
        base = pick_tone("normal")
        vibe = st.session_state.vibe
        vibe_line = f"Vibe: {vibe}/5. Keeping it concise." if vibe <= 3 else f"Vibe: {vibe}/5. We can go a bit bolder."
        return (
            f"{base}\n{vibe_line}\n\n"
            "Template:\nDone:\n- \n\nNext:\n- \n\nBlockers/Risks:\n- \n\nAsk (if any):\n- "
            + (f"\n\n{nudge}" if nudge else "")
        )

    if any(k in low for k in ["email", "mail", "slack", "teams", "message"]):
        base = pick_tone("normal")
        return (
            f"{base}\n\n"
            "Tell me: audience, ask, deadline, tone.\n\n"
            "Draft template:\n"
            "Subject: [Action] [Topic] by [Date]\n\n"
            "Hi [Name],\n"
            "Quick update on [topic].\n\n"
            "Status:\n- \n\n"
            "Next steps (Owner | Date):\n- \n\n"
            "Decision/ask:\n- \n\n"
            "Thanks,\n[Your name]"
            + (f"\n\n{nudge}" if nudge else "")
        )

    if any(k in low for k in ["agenda", "meeting agenda"]):
        base = pick_tone("normal")
        return (
            f"{base}\n\n"
            "30-min agenda:\n"
            "1) Outcomes (2)\n"
            "2) Progress (8)\n"
            "3) Decisions (8)\n"
            "4) Risks (6)\n"
            "5) Next steps (6)\n\n"
            "Send topic + attendees + desired decision."
            + (f"\n\n{nudge}" if nudge else "")
        )

    if any(k in low for k in ["raid", "risk", "issue", "blocker", "dependency", "assumption"]):
        base = pick_tone("normal")
        return (
            f"{base}\n\n"
            "RAID entry:\n"
            "Type:\nDescription:\nImpact:\nLikelihood:\nOwner:\nMitigation:\nDue:\nStatus:\n\n"
            "Paste your sentence; I’ll format it."
            + (f"\n\n{nudge}" if nudge else "")
        )

    if any(k in low for k in ["slides", "deck", "ppt", "storyline"]):
        base = pick_tone("normal")
        return (
            f"{base}\n\n"
            "6-slide storyline:\n"
            "1) Context\n"
            "2) Current state\n"
            "3) Insights\n"
            "4) Options + trade-offs\n"
            "5) Recommendation\n"
            "6) Roadmap + risks\n\n"
            "Send audience + decision + time limit."
            + (f"\n\n{nudge}" if nudge else "")
        )

    # FAAH path
    if faah_hit:
        base = pick_tone("faah")
        roast = st.session_state.roast_level
        roast_line = ""
        if st.session_state.mode == "Roast-lite" and roast >= 2:
            roast_line = "Also: I can give you a polite pushback line that won’t start a thread-war."
        return (
            f"{base}\n\n"
            "Fast idea structure (client-safe):\n"
            "A) Optimize (low risk)\n"
            "B) Enable (medium)\n"
            "C) Transform (bold)\n\n"
            "Give 3 inputs: objective, constraints, decision-maker.\n"
            + (f"\n\n{roast_line}" if roast_line else "")
            + (f"\n\n{nudge}" if nudge else "")
        )

    # Default
    base = pick_tone("normal")
    return (
        f"{base}\n\n"
        "Try: email / standup / agenda / RAID / slides.\n"
        "Or use: /slang, /questions, /todo, /recap."
        + (f"\n\n{nudge}" if nudge else "")
    )

# =============================
# Sidebar controls
# =============================
with st.sidebar:
    st.subheader("Bot settings")
    st.session_state.mode = st.selectbox("Mode", ["GenZ", "Client-safe", "Hinglish", "Roast-lite"], index=["GenZ","Client-safe","Hinglish","Roast-lite"].index(st.session_state.mode))
    st.session_state.vibe = st.slider("Vibe (1 low to 5 high)", 1, 5, int(st.session_state.vibe))
    st.session_state.roast_level = st.slider("Roast level (safe)", 0, 3, int(st.session_state.roast_level))

    st.divider()
    st.subheader("Work hours")
    c1, c2 = st.columns(2)
    with c1:
        st.session_state.work_start = st.number_input("Start hour", 0, 23, int(st.session_state.work_start))
    with c2:
        st.session_state.work_end = st.number_input("End hour", 1, 24, int(st.session_state.work_end))

    st.divider()
    st.subheader("Soundboard")
    up = st.file_uploader("Upload faah.mp3 or faah.wav", type=["mp3", "wav"], key="faah_upl")
    if up is not None:
        st.session_state.faah_upload_bytes = up.getvalue()
        st.session_state.faah_upload_name = up.name
        st.session_state.faah_upload_mime = up.type or ("audio/mpeg" if up.name.lower().endswith(".mp3") else "audio/wav")
        st.success(f"Loaded FAAH: {up.name}")

    up2 = st.file_uploader("Upload celebrate.mp3 or celebrate.wav", type=["mp3", "wav"], key="cel_upl")
    if up2 is not None:
        st.session_state.celebrate_upload_bytes = up2.getvalue()
        st.session_state.celebrate_upload_name = up2.name
        st.session_state.celebrate_upload_mime = up2.type or ("audio/mpeg" if up2.name.lower().endswith(".mp3") else "audio/wav")
        st.success(f"Loaded Celebrate: {up2.name}")

    try_autoplay = st.toggle("Attempt autoplay", value=True)

    if st.button("Enable Sound (required once)"):
        st.session_state.sound_unlocked = True
        st.success("Sound unlocked for this session.")
        st.session_state.audio_nonce += 1
        js_play_audio_now(make_silence_wav(80), "audio/wav", st.session_state.audio_nonce, volume=0.0)

    st.caption("Tip: FAAH triggers on ‘Client wants new ideas by EOD’, ‘ASAP’, ‘small change’, etc.")

    st.divider()
    st.subheader("Celebrate FX")
    celebrate_fx = st.radio("Effect", ["Balloons", "Snow (sprinkle)", "Toast + Ding", "Off"], index=0)

    st.divider()
    st.subheader("Quick prompts")
    if st.button("FAAH: new ideas by EOD"):
        st.session_state._queued_input = "Client wants new ideas by EOD, same budget."
    if st.button("FAAH: small change, make it pop"):
        st.session_state._queued_input = "It’s a small change, just make it pop."
    if st.button("Celebrate: approved"):
        st.session_state._queued_input = "Good news! Client approved the approach."
    if st.button("Show slang"):
        st.session_state._queued_input = "/slang"
    if st.button("Show questions"):
        st.session_state._queued_input = "/questions"
    if st.button("Recap"):
        st.session_state._queued_input = "/recap"
    if st.button("Play FAAH now"):
        st.session_state._queued_input = "/faah"

    st.divider()
    st.subheader("Export / Import")
    export_obj = {
        "exported_at": dt.datetime.now().isoformat(timespec="seconds"),
        "mode": st.session_state.mode,
        "vibe": st.session_state.vibe,
        "roast_level": st.session_state.roast_level,
        "work_hours": {"start": st.session_state.work_start, "end": st.session_state.work_end},
        "messages": st.session_state.messages,
        "todos": st.session_state.todos,
        "stats": st.session_state.stats,
    }
    st.download_button(
        "Download chat JSON",
        data=json.dumps(export_obj, indent=2).encode("utf-8"),
        file_name="office_genz_bot_export.json",
        mime="application/json",
    )

    imp = st.file_uploader("Import chat JSON", type=["json"], key="import_json")
    if imp is not None:
        try:
            obj = json.loads(imp.getvalue().decode("utf-8"))
            if isinstance(obj.get("messages"), list):
                st.session_state.messages = obj["messages"]
            if isinstance(obj.get("todos"), list):
                st.session_state.todos = obj["todos"]
            if isinstance(obj.get("stats"), dict):
                st.session_state.stats = obj["stats"]
            st.success("Imported.")
        except Exception as e:
            st.error(f"Import failed: {e}")

# =============================
# Header
# =============================
st.markdown(
    """
<div class="hero">
  <div class="title">Office GenZ Bot • FAAH on stress</div>
  <div class="sub">
    Commands:
    <span class="kbd">/mode</span>
    <span class="kbd">/vibe</span>
    <span class="kbd">/slang</span>
    <span class="kbd">/questions</span>
    <span class="kbd">/todo</span>
    <span class="kbd">/recap</span>
    <br><br>
    FAAH triggers on:
    <span class="kbd">Client wants new ideas by EOD</span>
    <span class="kbd">ASAP</span>
    <span class="kbd">small change</span>
    <span class="kbd">make it pop</span>
    <br><br>
    Good news triggers:
    <span class="kbd">approved</span>
    <span class="kbd">we won</span>
    <span class="kbd">go-live</span>
  </div>
</div>
""",
    unsafe_allow_html=True,
)

# =============================
# Input
# =============================
queued = st.session_state.get("_queued_input")
if queued:
    st.session_state._queued_input = None

user_text = queued or st.chat_input("Type here… (e.g., Client wants new ideas by EOD)")

# =============================
# Handle message
# =============================
faah_hit = False
good_hit = False
faah_hit_keys = []

if user_text:
    ts = dt.datetime.now().strftime("%H:%M")
    st.session_state.messages.append({"role": "user", "content": user_text, "ts": ts})
    st.session_state.stats["msg_count"] += 1

    faah_manual = (user_text.strip().lower() == "/faah")
    faah_hit, faah_hit_keys = should_play_faah(user_text)
    faah_hit = faah_manual or faah_hit

    good_hit = is_good_news(user_text)

    # Update stats
    if faah_hit:
        st.session_state.stats["faah_count"] += 1
        for k in faah_hit_keys:
            st.session_state.stats["top_triggers"][k] = st.session_state.stats["top_triggers"].get(k, 0) + 1
    if good_hit:
        st.session_state.stats["good_count"] += 1

    reply = office_reply(user_text, faah_hit=faah_hit, good_hit=good_hit)
    st.session_state.messages.append({"role": "assistant", "content": reply, "ts": ts})

# =============================
# FX (good news)
# =============================
if good_hit and celebrate_fx != "Off":
    if celebrate_fx == "Balloons":
        st.toast("Big W. Approved / go-live vibes.")
        st.balloons()
    elif celebrate_fx.startswith("Snow"):
        st.toast("Sprinkle time. Good news locked.")
        st.snow()
    elif celebrate_fx.startswith("Toast"):
        st.toast("Toast: good news just dropped.")
        if "try_autoplay" in locals():
            play_celebrate_immediately(try_autoplay=try_autoplay)

# =============================
# FAAH sound
# =============================
if faah_hit:
    if "try_autoplay" in locals():
        play_faah_immediately(try_autoplay=try_autoplay)

# =============================
# Chat history + mini analytics
# =============================
st.markdown('<div class="card">', unsafe_allow_html=True)
st.markdown(
    f'<div class="small">Mode: {st.session_state.mode} | Vibe: {st.session_state.vibe}/5 | FAAH: {st.session_state.stats["faah_count"]} | Good: {st.session_state.stats["good_count"]}</div>',
    unsafe_allow_html=True,
)

# Show top triggers (compact)
top = sorted(st.session_state.stats["top_triggers"].items(), key=lambda x: x[1], reverse=True)[:5]
if top:
    st.markdown(
        "<div class='small'>Top FAAH triggers: "
        + ", ".join([f"{k}({v})" for k, v in top])
        + "</div>",
        unsafe_allow_html=True,
    )

for m in st.session_state.messages:
    with st.chat_message(m["role"]):
        st.markdown(m["content"])
        st.markdown(f'<div class="small">{m["ts"]}</div>', unsafe_allow_html=True)

st.markdown("</div>", unsafe_allow_html=True)




